### PR TITLE
Add button to display congrats message

### PR DESCRIPTION
**Pull request by alexperkins**
Added some stuff

### CODE REVIEW

**Comment by domfarolino** [comment]
I haven't looked at this at all, sorry @aperks7 for the massive delay. @isiah-lloyd what do you think of this (I haven't looked at the surrounding code nor the changed code though, but figured we should probably see what's going on).

**Comment by isiah-lloyd** [comment]
@domfarolino Lol, this is the pull request we have people make during the Git workshop.

**Comment by domfarolino** [comment]
Hahahahah ughhhhhhhhhhhhhh

**Comment by alexperkins** [comment]
It's been a while since I've used Git but I closed this PR because I wanted to clean up my Github. I hope I did it right lol.

**Comment by isiah-lloyd** [comment]
@aperks7 Yeah you did, Dom just didn't see the context of the PR hahaha.

**Pull request closed without merging**
